version: '3'

services:
  shop_client-front:
    command: "npm run dev"
    volumes:
      - ./client-next/app/pages:/usr/src/app/pages
      - ./client-next/app/components:/usr/src/app/components
      - ./client-next/app/styles:/usr/src/app/styles
